- name: Deploy Maven JAR
  hosts: app
  tasks:
    - name: Ensure target directory exists
      file:
        path: /var/lib/jenkins/workspace/deploy-output
        state: directory
        mode: '0755'

    - name: Copy JAR file
      copy:
        src: ../target/my-app-1.0-SNAPSHOT.jar
        dest: /var/lib/jenkins/workspace/deploy-output/myapp.jar
