- name: Deploy Maven JAR
  hosts: app
  tasks:
    - name: Ensure target directory exists
      file:
        path: /opt/my-app
        state: directory
        mode: '0755'

    - name: Copy JAR file
      copy:
        src: ../target/my-app-1.0-SNAPSHOT.jar
        dest: /opt/myapp/myapp.jar
